name: End-to-End Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'wizdemo'

# Add permissions here to match those required by called workflows
permissions:
  deployments: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
        environment: ${{ github.event.inputs && github.event.inputs.environment || 'wizdemo' }}
    secrets: inherit
    
  build:
    uses: ./.github/workflows/build-images.yml
    needs: terraform
    with:
      acr_name: ${{ needs.terraform.outputs.acr_name }}
    secrets: inherit
    
  deploy:
    needs: [build, terraform]
    uses: ./.github/workflows/kubernetes-deploy.yml
    with:
      environment: ${{ github.event.inputs && github.event.inputs.environment || 'wizdemo' }}
      acr_name: ${{ needs.terraform.outputs.acr_name }}
      aks_cluster_name: ${{ needs.terraform.outputs.aks_cluster_name }}
    secrets: inherit